# Server
server.port=8080

# Database
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/afroverbo
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=1234567
SPRING_JPA_HIBERNATE_DDL_AUTO=update

# Mail
MAIL_USERNAME=ronaldoburah3@gmail.com
MAIL_PASSWORD=sbgiblpfbxoocgoq

# JWT
JWT_SECRET=afroverbo_local_secret_key_2024

# Logging
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Daraja
DARAJA_MOCK_ENABLED=true
